#!/bin/bash

  # -----------------------------------------------------------------------------------
  while (( "$#" ))
  do case $1 in
       -p|--path) shift && path="$1"  ;;
     esac
     shift
  done

  if [[ -z $path ]]
  then echo "... Please provide full path to where the UCM Module is cloned."
       exit 1
  fi 

  
  if [[ ! -d $path ]]
  then echo "... Path: \"$path\" not found.  Bailing"
       exit 1
  fi 

  # -----------------------------------------------------------------------------------
  dirmain="/etc/puppet"
  dirpup="${dirmain}"
  dircode="${dirmain}"
  direnv="${dircode}/environments/production"
  dirmod="${direnv}/modules"
  hiera_config="${path}/files/main/hiera/hiera.3x.masterless.npe.yaml"
  hiera_dest="${dirpup}/hiera.yaml"
  dirdata="${dircode}/hiera/production/hieradata"
  pconf="${dirpup}/puppet.conf"
  
  # -----------------------------------------------------------------------------------
  echo "... Setting up local masterless Puppet for P5."
  echo ""

  echo "... making sure hiera data dir exists."
  mkdir -p $dirdata

  echo "... making sure environments dir exists."
  mkdir -p $direnv

  echo "... copying hiera yaml in place."
  cp $hiera_config $hiera_dest
  cp $hiera_config /etc/hiera.yaml

  echo "... copying common.yaml in place."
  cp ${path}/files/main/common.yaml $dirdata

  echo "... making soft link to modpath in datadir"
  cd $dirdata 
  ln -s $dirmod >/dev/null 2>&1

  echo "... copying ucm mod in place"
  cp -rp $path $dirmod >/dev/null 2>&1
  rm -rf ${dirmod}/.git

  echo "... making soft links in root's dir homedir"
  cd /root/
  ln -s $dirpup >/dev/null 2>&1
  ln -s $dirmod >/dev/null 2>&1
  ln -s $hiera_dest >/dev/null 2>&1
  ln -s $dirdata >/dev/null 2>&1
  ln -s $pconf >/dev/null 2>&1
  echo ""

  echo "... copying all global scripts to /usr/local/bin"
  cp -rp ${path}/bin/global/* /usr/local/bin >/dev/null 2>&1

  echo "... running puppet apply of local test class, which includes a hiera lookup."
  echo "" 
  # puppet apply -t -e 'include ucm::masterlesstest'
  puppet apply --environment=production --modulepath=/etc/puppet/environments/production/modules/ -e 'include ucm::masterlesstest'
  echo "" 
  
  
