#!/bin/bash


  if [[ -z $1 || -z $2 ]]
  then echo "... PLEASE PROVIDE FIRST FACTNAME THEN FACT VALUE"
       exit 1
  fi
  name=$1
  value=$2

  if [[ -d '/etc/puppetlabs/facter/facts.d' ]]
  then dirf='/etc/puppetlabs/facter/facts.d'
  else dirf='/etc/facter/facts.d'
  fi

  echo "${name}=${value}" > ${dirf}/${name}.txt
  echo ""
  echo "... FACT ${name}: `facter -p $name`"
  echo ""

