#!/bin/bash

  source /etc/environment
  PATH=$NEWPATH

  while (( "$#" ))
  do case $1 in
       -c|--class) shift && class="$1"    ;;
       -n|--noop)  shift && noop="--noop" ;;
     esac
     shift
  done

  if [[ -z $class ]]
  then echo "... Please provide the Puppet class you wish to test with -c or --class < class name >" ; exit 1
  fi

  env='production'
  modpath='/etc/puppetlabs/code/environments/production/modules/'

  echo ""
  echo "... Testing class: \"${class}\""
  echo ""
  puppet apply -t --show_diff --environment=${env} --modulepath=${modpath} $noop -e "include $class"
  echo ""
  echo ""

