#!/bin/bash

  yumdir='/etc/yum.repos.d'
  yumdirbackup='/root/yum.backup'
  yumdirhold='/root/yum.backup.hold'

  if [[ -f /root/tdaenv.new ]]
  then source /root/tdaenv.new
  else echo "... PLEASE CREATE /root/tdaenv.new FROM PRE RUN SCRIPT TO CONTINUE."
       exit 1
  fi

  thisrelease="`rpm -q --queryformat '%{VERSION}' redhat-release-server`"

  if [[ $thisrelease = '6Server' ]]
  then urlstringaddons='/yumrepos/mrepo/rhel-6-x86_64/RPMS.tda-addons/' ; urlstringepel='/yumrepos/mrepo/rhel-6-x86_64/RPMS.epel/'
  else urlstringaddons='/yumrepos/mrepo/rhel-7-x86_64/RPMS.tda-addons/' ; urlstringepel='/yumrepos/mrepo/rhel-7-x86_64/RPMS.epel/'
  fi

  mkdir -p $yumdirbackup $yumdirhold
  cp ${yumdir}/* ${yumdirbackup}/

  echo "-------------------------------------------------------------------------"
  echo "...ENSURING EPEL AND ADDONS IS ENABLED"
  echo "-------------------------------------------------------------------------"

cat <<EOF >/etc/yum.repos.d/addons.repo
[addons]
name=addons
baseurl=http://${buildserver}${urlstringaddons}
enabled=1
gpgcheck=0
EOF

