#!/bin/bash

  tarball='/tmp/unitycm-installer.tar.gz'
  dirmain="/etc/puppetlabs"
  dirpup="/etc/puppetlabs/puppet"
  dircode="${dirmain}/code"
  direnv="${dircode}/environments/production"
  dirmod="${direnv}/modules"
  dirucm="${dirmod}/ucm"
  hiera_config="${dirmod}/ucm/files/main/hiera/hiera.yaml.localtesting.2019"
  hiera_dest="${dirpup}/hiera.yaml"
  dirdata="${dircode}/hiera/production/hieradata"
  pconf="${dirpup}/puppet.conf"
  git_ucm='ssh://git@bitbucket.associatesys.local/sme/ucm.git'
  git_base='ssh://git@bitbucket.associatesys.local/sme/base.git'
  ver_puppet="`puppet --version | awk -F "." '{print $1}'`"
  git --version >/dev/null 2>&1
  if [[ $? != '0' ]] ; then git=false ; else git='true' ; fi
  if [[ ! -f /root/.ssh/id_rsa.pub ]] ; then sshkey='false' ; fi
 
  cat /etc/tda/env  | grep -v HOSTNAME | tr '[:upper:]' '[:lower:]' > /etc/facter/facts.d/tdaenv.txt
  echo 'NEWPATH=/usr/ucb:/usr/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/opt/puppetlabs/bin:/root/bin:/opt/puppet/bin' >> /etc/environment
  

  # -----------------------------------------------------------------------------------
  # Making sure we're on Puppet 5
  if [[ $ver_puppet != '5' ]]
  then echo "... This server \"`uname -n`\" has not been upgraded to Puppet 5, bailing." ; exit 1
  else echo "... Checking/Setting up local testing config."
  fi

  # -----------------------------------------------------------------------------------
  # Making sure Git is installed
  if [[ $git != 'true' ]]
  then echo "... Attempting to install git."
       echo "" ; yum install -y git ; echo ""
  fi

  git --version >/dev/null 2>&1
  if [[ $? != '0' ]]
  then echo "... Git doesn't appear installed, maybe check on yum? Bailing." ; exit 1
  fi

  # -----------------------------------------------------------------------------------
  if [[ ! -d $dirmod ]]
  then echo "... Creating environment/modules directory for you data modules." ; mkdir -p $dirmod
  fi

  if [[ ! -d $dirdata ]]
  then echo "... Creating data directory." ; mkdir -p $dirdata
  fi

  # -----------------------------------------------------------------------------------
  # Making sure we have the ucm module cloned correctly
  if [[ ! -d ${dirmod}/ucm ]]
  then echo "... Attempting to clone the \"UCM\" Puppet Module."
    if [[ $sshkey = 'false' ]]
    then echo "... Please setup the default ssh key for root before proceeding." ; exit 1
    else echo "" ; cd $dirmod && git clone $git_ucm -b release ; echo ""
      if [[ ! -d ${dirmod}/ucm ]]
      then echo "... Uh oh, doesn't seem we cloned the UCM module correctly.  Network connectivity?  Bailing." ; exit 1
      fi

      if [[ ! -f ${dirmod}/ucm/manifests/init.pp ]]
      then echo "... Doesn't seem we cloned the UCM Module correctly.  Bailing."
           rm -rf ${dirmod}/ucm ; exit 1
      fi
    fi
  fi

  cd $dirucm ; git pull origin `git branch  | grep '\*'  | awk '{print $NF}'` --quiet >/dev/null 2>&1

  # -----------------------------------------------------------------------------------
  # Making sure we have the ucm module cloned correctly
  if [[ ! -d ${dirmod}/base ]]
  then echo "... Attempting to clone the \"base\" Puppet Module."
    if [[ $sshkey = 'false' ]]
    then echo "... Please setup the default ssh key for root before proceeding." ; exit 1
    else echo "" ; cd $dirmod && git clone $git_base -b release ; echo ""
      if [[ ! -d ${dirmod}/base ]]
      then echo "... Uh oh, doesn't seem we cloned the base module correctly.  Network connectivity?  Bailing." ; exit 1
      fi

      if [[ ! -d ${dirmod}/base/data ]]
      then echo "... Doesn't seem we cloned the base Module correctly.  Bailing."
           rm -rf ${dirmod}/base ; exit 1
      fi
    fi
  fi

  cd ${dirmod}/base ; git pull origin `git branch  | grep '\*'  | awk '{print $NF}'` --quiet >/dev/null 2>&1

  # -----------------------------------------------------------------------------------
  cp $hiera_config $hiera_dest
  cp ${dirucm}/files/main/common.yaml $dirdata

  cd $dirdata
  ln -s $dirmod >/dev/null 2>&1

  echo "... making soft links in root's dir homedir"
  cd /root/
  ln -s $dirpup >/dev/null 2>&1
  ln -s $dirmod >/dev/null 2>&1
  ln -s $dirucm >/dev/null 2>&1
  ln -s $hiera_dest >/dev/null 2>&1
  ln -s $dirdata >/dev/null 2>&1
  ln -s $pconf >/dev/null 2>&1

  cp -rp ${dirucm}/unibin/uni/* /usr/local/bin >/dev/null 2>&1
  /usr/local/bin/setfact -f ucmos -v base >/dev/null 2>&1
  /usr/local/bin/setfact -f child -v p3   >/dev/null 2>&1

  echo "... running puppet apply of local test class, which includes a hiera lookup."
  echo ""
  puppet apply -t -e 'include ucm::masterlesstest'
  echo ""


