---
- hosts: all
  name: Install the fact to set the maintenance window to be closed
  tasks:
    - name: Set the maintenance window to be closed
      copy:
        dest: /etc/ansible/facts.d/
        src: custom.fact

    - name: Disallow root to login via SSH with the maintenance window set to closed
      lineinfile:
        dest: /etc/ssh/sshd_config
        state: present
        regexp: PermitRootLogin yes
        line: PermitRootLogin no

    - name: Allow regular users to login with the maintenance window set to closed 
      file:
        path: /etc/nologin
        state: absent

    - name: All cron to run with the maintenance window set to closed
      service:
        name: crond
        state: started

...
