---
- name: Template to setup a webserver
  hosts: webservers
  tasks:
    - name: Include the variables
      include_vars: vhost.vars

    - name: Install the webserver software
      yum:
        name: httpd
        state: installed

    - name: Create the custom vhost document root
      file:
        state: directory
        owner: apache
        mode: 000755
        path: /vhosts/{{ ansible_fqdn }}/html
        setype: httpd_sys_content_t

    - name: Render the configuration from a j2 template
      template:
        src: vhost.template.j2
        dest: /etc/httpd/conf.d/{{ ansible_hostname}}.conf
        owner: apache
        group: root
        mode: 000644

    - name: Install sample content
      copy:
        content: "This is {{ ansible_fqdn }}\n"
        dest: /vhosts/{{ ansible_fqdn }}/html/index.html
        setype: httpd_sys_content_t

    - name: Start and enable the webserver
      service:
        name: httpd
        state: restarted
        enabled: yes

    - name: Open the port in the firewall
      firewalld:
        service: http
        state: enabled
        immediate: true
        permanent: true
...
