---
- name: Create users
  hosts: servera.lab.example.com
  vars:
    myusers:
      - fred
      - barney
      - wilma
      - betty

  tasks:

    - name: Create users
      user:
        name: "{{ item }}"
        state: absent
      with_items: "{{ myusers }}"
...
