---
- hosts: databases
  vars:
    web_package: http
    db_package: mariadb-server
    db_service: mariadb

  tasks:
    - block:
      - name: Install {{ web_package }} package
        yum:
          name: "{{ web_package }}"
          state: latest
      rescue:
        - name: Install {{ db_package }} package
          yum:
            name: "{{ db_package }}"
            state: latest
      always:
        - name: Start {{ db_service }} 
          service: 
            name: "{{ db_service }}" 
            state: started

