#!/bin/bash

  while (( "$#" ))
  do case $1 in
       --exists) shift && option_exists='true'          ;;
       --is_deployed) shift && option_isdeployed='true' ;;
       -s|--server) shift && server="$1"                ;;
     esac
     shift
  done

  if [[ -z $server ]]
  then echo "... please provide server name with -s or --server <server name>"
       exit 1
  fi 

  domain="`echo $server | awk -F '.' '{print 2}'`"
  if [[ ! -z $domain ]]
  then node="`echo $server | awk -F '.' '{print $1}'`" 
  else node="$server"
  fi 

  fn_exists () {
    node=$1
    /app/utils/scripts/servinfo -s $node | grep 'TADDM_FQDN' >/dev/null 2>&1
    if [[ $? = '0' ]] 
    then exit 0
    else exit 1
    fi
  } 

  fn_isdeployed () {
    node=$1
    status="`/app/utils/scripts/servinfo -s $node | grep AssetLifecycleStatus | awk -F ":" '{print $NF}' | tr '[:upper:]' '[:lower:]'`"
    if [[ $status = 'deployed' ]] 
    then exit 0
    else exit 1
    fi
  }

  if [[ $option_exists = 'true' ]] 
  then fn_exists $node
  fi 

  if [[ $option_isdeployed = 'true' ]] 
  then fn_isdeployed $node
  fi 
