#!/bin/bash
  source /etc/environment
  PATH=$NEWPATH

  opts='-k'
  host="ucmnui.associatesys.local"
  url="https://${host}/api/v2"
  url_h="${url}/hosts"
  url_h_name="${url}/hosts/${server}"
  user='ucmadmin'
  pw='unity2018'
  h_type='Content-Type:application/json'
  h_accept='Accept:application/json'
  msg_err="resource host not found"

  if [[ ! -d /rdc_migration/ucm/pmdb ]] 
  then echo "... no /rdc_migration/ucm/pmdb/ found"
       exit 1
  fi 

  curl $opts -u "${user}:${pw}" -H "$h_type" -H "$h_accept" ${url_h}?per_page=99999 | python -m json.tool | tee /rdc_migration/ucm/pmdb/ucm_fman_dump.json
  grep '"certname":' /rdc_migration/ucm/pmdb/ucm_fman_dump.json | sed 's/[",\,]//g ; s/           certname: //g' > /rdc_migration/ucm/pmdb/hosts_ucm
