#!/bin/bash

  while (( "$#" ))
  do case $1 in
       -e|--environment) shift && env="$1"  ;;
     esac
     shift
  done

  # Require fact indicating we can run this script on this server
  is_sync="`facter is_sync`"
  if [[ $is_sync != 'true' ]] 
  then echo "...This is not a sync server, bailing."
       exit 1
  fi 

  if [[ -z $env ]]
  then echo "... please provide environment name with -e or --environment <server name>" ; echo "" 
       exit 1
  fi  

  if [[ ! -d /root/environments/${env} ]] 
  then echo "... hmm, didn't find that env in the envs dir"
       echo "" 
       ls -l /root/environments/
       echo "" 
       exit 1
  fi 

  fn_cloner () {
    # Need to cd to the dir to clone
    name=$1 url=$2 branch=$3
    if [[ ! -d $name ]] 
    then echo "... Environment: \"$env\", Cloning: \"$name\" "
    
      if [[ -z $branch ]] 
      then git clone $url 
      else git clone $url -b $branch
      fi 
 
    else echo "... Environment: \"$env\", Already have \"$name\" cloned"
    fi 
  } 

  cd /root/environments/${env}/modules 
  fn_cloner base ssh://git@bitbucket.associatesys.local/sme/base.git release 
  fn_cloner ucm ssh://git@bitbucket.associatesys.local/sme/ucm.git  release 
