#!/bin/bash

# THIS SCRIPT DOES THE FOLLOWING
# - FIRST CHECKS IF WE'RE IN A GIT DIRECTORY
# - CLEANS THE REPO STATE BY UNCOMMITTING ANY CHANGED FILES
# - CHECKS IF THE REPO STATE IS CLEAN, BAILS IF NOT
# - CHECKS IF THE DEFAULT BRANCH 'RELEASE' EXISTS IN THE REMOTE VERSION OF THE REPO (JUST INCASE), BAILS IF NOT
# - CHECKS IF THE CURRENT BRANCH IS THE DEFAULT BRANCH, SWITCHES IF NOT, FAILS IF COULD NOT SWITCH FOR WHAT EVER REASON
# - PULLS THE LATEST VERSION OF THE BRANCH, FAILS IF COULD NOT PULL SUCCESSFULLY

  while (( "$#" )); do
    case $1 in
      -m|--message) shift && message="$1"  ;;
    esac
    shift
  done  

  # ----------------------------------------------------------------------------------------------
  if [[ `whoami` = 'root' ]] 
  then echo "... YOU SHOULD NOT BE RUNNING THIS SCRIPT AS ROOT, BAILING." 
       exit 1
  fi 
 
  branch='release'
  branchexists () {
    checkbranch=$1
    if git branch -a | sed 's/remotes\/origin\///g' | grep -q $checkbranch
    then echo "true"
    else echo "false"
    fi
  }

  check_if_git () {
    git rev-parse --git-dir >/dev/null 2>&1
    if [[ $? != 0 ]]
    then echo "... THIS DIRECTORY IS NOT A GIT REPOSITORY" ; exit 1
    fi
  }

   gitpull () {
    git pull origin `tgit -b` >/dev/null 2>&1
    if [[ $? == '0' ]]
    then echo "true"
    else echo "fail"
    fi
  }

   gitpush () {
    git push origin `tgit -b` >/dev/null 2>&1
    if [[ $? == '0' ]]
    then echo "true"
    else echo "fail"
    fi
  }

  # ----------------------------------------------------------------------------------------------
  check_if_git

  # DOCTOR OBVIOUS
  echo "" 
  echo "... YOU ARE IN GIT REPOSITORY: \"`tgit -r`\" "

  porcelain="`git status --porcelain`"
  if [[ -z $porcelain ]] 
  then echo "... STATUS IS CLEAN, NO CHANGES DETECTED TO COMMIT." ; echo "" 
       exit 1
  fi 

  cd "$(git rev-parse --show-toplevel)" >/dev/null 2>&1
  git add .                             >/dev/null 2>&1
  echo "... YOUR STATUS BEFORE COMMITTING:"
  echo "---------------------------------------------------------------------------------------"  
  echo ""
  git status
  echo "" 
  echo "" 
  sleep 3

  git commit -a -m "OPSGIT: CHANGES MADE BY: \"`whoami`\" $message" >/dev/null 2>&1
  if [[ $? = '0' ]]
  then echo "... SUCCESSFULLY COMMITED CHANGE" 
  else echo "... FAILED TO COMMIT CHANGE FOR SOME REASON, BAILING" ; exit 1
  fi

  # PULL
  if [[ `gitpush` = 'true' ]] 
  then echo "... SUCCESSFULLY PUSHED CHANGE TO BRANCH: $branch"
       if [[ ! -z $message ]] 
       then echo "... COMMITTED WITH MESSAGE: \"$message\" "
       fi 
       echo "... CURRENT REVISION ENDS IN: `tgit -rv | tail -c 5`"
  else echo "... FAILED TO PUSH BRANCH $branch" ; exit 1
  fi  

  # LAST ECHO 
  echo ""  

  
