#!/bin/bash

  path='/home/cor846/git'
  server=$1

 while (( "$#" ))
  do case $1 in
       -s|--server) shift && server="$1"  ;;
     esac
     shift
  done

  if [[ -z $server ]]
  then echo "... Please provide server fqdn with -s or --server"
       exit 1
  fi 

  cd /ulse/ucm
  # scp tarballs/unitycm-installer.tar.gz tarballs/salt.tar.gz /ulse/ucm/unitycm-installer/ucm/bin/unitycm-installer.local `whoami`@${server}:/tmp
  sudo scp -o "StrictHostKeyChecking=no" -i /root/sudossh.privkey tarballs/unitycm-installer.tar.gz tarballs/salt.tar.gz /ulse/ucm/unitycm-installer/ucm/bin/unitycm-installer.local root@${server}:/tmp

