#!/bin/bash

  source /etc/environment
  PATH=$NEWPATH

  while (( "$#" ))
  do case $1 in
       -s|--server) shift && server="$1"   ;;
       --lock-dir) shift && lockdir="$1"   ;;
       --proof-dir) shift && proofdir="$1" ;;
     esac
     shift
  done

  me="`hostname`"
  saltmaster="prdtxlvpptapp03"
  if [[ $me != $saltmaster ]] 
  then echo "Must run this script on salt master"
       exit 1
  fi 

  # just a little idempotent redundancy

  if [[ ! -d $proofdir ]] 
  then mkdir -p $proofdir
  fi 

  if [[ ! -d $lockdir ]] 
  then mkdir -p $lockdir
  fi 

  parent='/etc/puppetlabs/code/ucm'
  bin="${parent}/git/ucm/unibin"
  cache="${parent}/cache"
  lockfile="${lockdir}/${server}.lock"
  prooffile="${proofdir}/${server}"

  mkdir -p $lockdir
  touch $lockfile

  ${bin}/api/host-lastreport -s $server -t 
  if [[ $? = '0' ]] 
  then echo "Splunk-upload-foreman-report Uploading: $server"
       ${bin}/api/hec-upload $server
       touch ${prooffile}.uploaded 
       rm -f $lockfile 
        
  else echo "Splunk-upload-foreman-report Skipping:  $server" 
       rm -f $lockfile 
       touch ${prooffile}.skipped
  fi 
