#!/bin/bash

  while : 
  do clear 
     echo "" 
     echo "TIME: `date`"
     echo "" 
     echo "`hostname -f` Freemem:     \"`free -g | grep Mem | awk '{print $4}'` GB\" " 
     echo "`hostname -f` Cpu:         \"`mpstat | awk '$3 ~ /CPU/ { for(i=1;i<=NF;i++) { if ($i ~ /%idle/) field=i } } $3 ~ /all/ { printf("%d%%",100 - $field) }'`\" " 
     echo "`hostname -f` Connections: \"`netstat -nap | grep 8140 | wc -l`\"" 
     echo "" 
     sleep 1 
  done

