#!/bin/bash

  file="$1"

  if [[ -z $file ]] 
  then echo "...Please provide path to file of servers to nslookup"
       exit 1
  fi 

  if [[ ! -f $file ]] 
  then echo "...Please provide a valid File of servers to nslookup"
       exit 1
  fi 

  filename="`echo $file | awk -F '/' '{print $NF}'`"


  for i in `cat $file` ; do 
    host $i > /dev/null 2>&1
      if [[ $? = 0 ]] 
      then host $i 
      else echo "...${i}_failed_to_lookup"
      fi 
  done | awk '{print $1, $NF}' | column -t | tee ./${filename}-dnsoutput.txt

  grep -v failed_to_lookup ./${filename}-dnsoutput.txt > ./${filename}-dnsoutput.good.txt
  grep failed_to_lookup ./${filename}-dnsoutput.txt > ./${filename}-dnsoutput.bad.txt
  echo "" 
  echo "Made files:"
  echo "./${filename}-dnsoutput.txt"
  echo "./${filename}-dnsoutput.good.txt"
  echo "./${filename}-dnsoutput.bad.txt"
  echo ""
