#!/bin/bash

  # Either super lazy, or effecient.
  git branch > /dev/null 2>&1
  if [[ $? != '0' ]] ; then echo "...Not in a git repo" ; exit 1; fi
  echo "" 
  echo "======================================================================================"
  echo "" 
  echo "--- PULLING - latest before commiting..."
  echo "- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - "  
  echo ""
  git pull origin `tgit -b`

  echo ""
  echo ""
  echo ""
  echo "--- COMMITTING - to branch `tgit -b`" 
  echo "- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - "  
  echo "" 
  git add .
  git commit -a -m '...' 

  echo ""
  echo ""
  echo ""
  echo "--- PUSHING - to branch `tgit -b`" 
  echo "- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - "  
  echo ""
  git push origin `tgit -b`
  echo "" 
  echo ""
  
