#!/bin/bash 

  while (( "$#" ))
  do case $1 in
       -s|--server) shift && server="$1" ;;
     esac
     shift
  done

  if [[ -z $server ]]
  then echo "... please provide server name with -s or --server <server name>"
       exit 1
  fi 

  host $server >/dev/null 2>&1
  if [[ $? = '0' ]] 
  then exit 0
  else exit 1
  fi 

