#!/bin/bash

  class=$1
  echo "...syncing content"
  for i in `ls -1 /home/cor846/repos` ; do cp -r /home/cor846/repos/${i} /etc/puppetlabs/code/environments/ngoms_dev3/modules ; done
  cp -rp /home/cor846/data/hieradata /etc/puppetlabs/code/hiera/ngoms_dev3 ; echo ""
  puppet apply -t --environment=ngoms_dev3 --modulepath=/etc/puppetlabs/code/environments/ngoms_dev3/modules/ -e "include $class"


