#!/bin/bash


  pkg='telnet'

  which telnet >/dev/null 2>&1
  if [[ $? != '0' ]]
  then echo "... `uname -n` TELNET_NOT_INSTALLED"
       exit 1
  fi

  good='true'

  echo exit | telnet prdtxlvpptapp05.associatesys.local 8140 | grep -qi "Connected to"
  if [[ $? != '0' ]] ; then good='false' ; fi

  echo exit | telnet prdtxlvpptapp03.associatesys.local 4505 | grep -qi "Connected to"
  if [[ $? != '0' ]] ; then good='false' ; fi

  echo exit | telnet prdtxlvpptapp03.associatesys.local 4506 | grep -qi "Connected to"
  if [[ $? != '0' ]] ; then good='false' ; fi

  if [[ $good = 'true' ]]
  then echo "`uname -n` GOOD"
  else echo "`uname -n` BAD"
  fi


