#!/bin/bash
  
  # ------------------------------------------------------------------------------
  # This script checks basic things in a provided UCM Data module

  while (( "$#" ))
  do case $1 in
       -p|--path) shift && datamodpath="$1" ;;
     esac
     shift
  done

  if [[ ! -d $datamodpath ]] 
  then echo '... That path doesn't exist, or is a file?'
       exit 1
  fi 

  cd $datamodpath
  topdir="`tgit -t`"
  
  if [[ ! -d ${topdir}/data ]] 
  then echo '... No "data" directory found in $topdir " 
       exit 1
  fi 

  exit 0
  
 
