#!/bin/bash

  tarname=$1
  if [[ -z $tarname ]]
  then echo "... PLEASE PROVIDE TARBALL NAME IN /urepo/nonpackaged/ucm/tars/ ON REPOM SERVER"
       exit 1
  fi

  source /etc/tda/env
  dirmod='/etc/puppet/environments/production/modules'
  url="http://${BUILDSERVER}"
  tarpath="nonpackaged/ucm/tars"

  cd $dirmod && wget ${url}/${tarpath}/${tarname}
  cd $dirmod
  lastmod="`ls -ltr  | tail -1 | awk '{print $NF}'`"
  if ! echo "$lastmod" | grep '.tar.gz'
  then echo "... LAST MODDED FILE IS NOT A TARBALL, MAYBE RUN AGAIN?"
       exit 1
  else tar -xzf $lastmod
       echo ""
       echo ""
       rm -f *.tar.gz
       ls -ltr
       echo ""
  fi

