#!/bin/bash

  source /etc/environment
  node=$1
  state=$2
  dir_cache='/etc/puppetlabs/code/ucm/cache'
  dir_locks="${dir_cache}/locks.cgi"
  log="${dir_cache}/log/ucm-bus.log"
  cache_output="${dir_cache}/cgi/${node}.saltoutput"
  limit='3'
  line='-----------------------------------------------------------------------------'

  rmfile () {
    file=$1 ; if [[ -f $file ]] ; then rm -f $file ; fi 
  }

  stamp () {
    file=$1 ; echo "" >> $file ; echo $line >> $file ; echo "" >> $file ; date >> $file ; echo "" >> $file
  }

  lock () {
    option=$1
    if   [[ $option == '-l' ]] 
    then touch ${dir_locks}/${node}.lock
    elif [[ $option == '-u' ]] 
    then rm -f ${dir_locks}/${node}.lock
    fi
  }
  
  locks () {
    ls -l $dir_locks | wc -l 
  }

  saltrun () {
    rmfile $cache_output
    stamp  $log
    salt $node state.sls $state --out json | tee -a $log $cache_output
    /usr/local/bin/couch-update -s $node
    lock -u
  }


  # ------------------------------------------------------------------------------------- 
  if test `locks` -le $limit
  then lock -l 
       echo "Running salt for ${node}"
       saltrun &>/dev/null &disown
  else until test `locks` -le $limit 
       do echo "Waiting until other servers are finished.  Current count is `locks`. sleeping..."
          echo "Limit is $limit"
          sleep 1
       done 

       lock -l
       echo "Running salt for ${node}"
       saltrun &>/dev/null &disown
  fi 
  



