#!/bin/bash

  source /etc/environment
  PATH=$NEWPATH

  databranch=$1 environment=$2
  datagiturl="zgitlab@gitlab.associatesys.local:tools/data.git"

  if [[ -z databranch || -z $environment ]]
  then echo "... PLEASE PROVIDE FIRST DATA BRANCH, THEN ENVIRONMENT"
       exit 1
  fi

  hradir='/etc/puppetlabs/puppet/hiera'        hraenv="${hradir}/${environment}"

  if [[ ! -d $hraenv ]]
  then echo "... CLONING DATA REPO FOR ENV: \"$environment\" "

    cd $hradir
    git clone $datagiturl -b $databranch $environment >/dev/null 2>&1

    if [[ $? != '0' ]]
    then echo "... CLONING HIERA DATA PROJECT FOR ENVIRONMENT \"$environment\" FAILED."
    else echo "... CLONED HIERA DATA PROJECT FOR ENVIRONMENT \"$environment\" "
    fi

  else

    cd $hraenv
    git checkout -- .        >/dev/null 2>&1
    git fetch -a             >/dev/null 2>&1

    if [[ `tgit -b` != "$databranch" ]]
    then git checkout $databranch >/dev/null 2>&1

      if [[ $? != '0' ]]
      then echo "... COULD NOT CHECKOUT BRANCH: \"$databranch\" FOR ENVIRONMENT: \"$environment\" FAILED."
      else branchisgood='true'
      fi

    else branchisgood=true
    fi

    if [[ $branchisgood == 'true' ]]
    then git pull origin `tgit -b` >/dev/null 2>&1

      if [[ $? != '0' ]]
      then echo "... COULD NOT PULL BRANCH: \"$databranch\" FOR ENVIRONMENT: \"$environment\" FAILED."
      else echo "... PULLED BRANCH: \"$databranch\" FOR ENVIRONMENT: \"$environment\". "
           echo "... REVISION: \"...`tgit -rv | tail -c 5`\" "
      fi
    fi
  fi

