---
- hosts: all
  remote_user: root
  name: Install the fact to set the maintenance window to be open
  
  tasks:
    - name: Set the maintenance window to be open
      copy:
        dest: /etc/ansible/facts.d/
        src: custom.fact

    - name: Allow root to login via SSH with the maintenance indow open
      lineinfile:
        dest: /etc/ssh/sshd_config
        state: present
        regexp: PermitRootLogin no
        line: PermitRootLogin yes

    - name: Disallow regular logins while the maintenance window is open
      copy:
        dest: /etc/nologin
        content: "Maintenance window is currently open so no logins are allowed"

    - name: Stop all cron jobs from running while the maintenance window is open
      service:
        name: crond
        state: stopped

...
