#!/bin/bash

  while (( "$#" ))
  do case $1 in
       -t|--token) shift && token="$1"  ;;
     esac
     shift
  done

  if [[ -z $token ]]
  then echo "... Please provide user auth token found in your gitlab profile with -t <token>"
       exit 1
  fi 

  instance='gitlab.associatesys.local'

  # curl --header "PRIVATE-TOKEN: $token" "https://${instance}/api/v4/projects/1/variables"
  curl --header "PRIVATE-TOKEN: $token" "http://${instance}/api/v4/projects" | python -m json.tool


