#!/bin/bash



  # url='http://foreman.associatesys.local:5984'
  url='http://prdtxlvptfman01.associatesys.local:5984'
  db='storagedata'
  server='ucmtestserver1.clientsys.local'

  # curl -s ${url}/${db}/${server} | python -m json.tool
  curl -H "Content-type:application/json" -X POST ${url}/${db} -d '{"_id": "'"${server}"'"}' # | python -m json.tool

  echo "" 
  echo "" 



