#!/bin/bash

  url='http://gitlab.associatesys.local/api/v3'
  string='users'

  for i in 1 2 3 4 5 6 7 8 9 10  
  do curl -s -k -H "PRIVATE-TOKEN: FYJq9hAcnxjyrZ8zjYZ7" ${url}/${string}?per_page=99999&page=$i 
     echo "" 
     echo "" 
     echo "" 
     echo "" 
     echo "" 
     echo "" 
     sleep 5
  done 
  # curl -s -k -H "PRIVATE-TOKEN: FYJq9hAcnxjyrZ8zjYZ7" -H 'Accept: version=2,application/json' ${url}/${string}?page=1&per_page=99999 | python -m json.tool


