#!/bin/bash
  source /etc/environment
  PATH=$NEWPATH

  while (( "$#" )); do
    case $1 in
      -s|--server)    shift && server="$1"      ;;
      -t|--timestamp) shift && timestamp='true' ;;
    esac
    shift
  done

  opts='-s -k'
  host="ucmnui.associatesys.local"
  url="https://${host}/api/v2"
  url_report="${url}/hosts/${server}/config_reports/last"
  user='ucmadmin'
  pw='unity2018'
  h_type='Content-Type:application/json'
  h_accept='Accept:application/json'
  msg_err="resource host not found"

  if [[ -z $server ]]
  then echo "... PLEASE PROVIDE -s < SERVER NAME >" ; exit 1
  fi

  if [[ -z `echo $server | awk -F '.' '{print $2}'` ]]
  then echo "... SERVER NAME MUST BE FQDN." ; exit 1
  fi

  host $server >/dev/null 2>&1
  if [[ $? != '0' ]]
  then echo "... COULD NOT RESOLVE $server" ; exit 1
  fi

  if [[ $timestamp = 'true' ]] 
  then timestamp="`curl $opts -u "${user}:${pw}" -H "$h_type" -H "$h_accept" $url_report | python -m json.tool | grep -i "created_at"`"
       now="`date +"%Y%m%d"`"
       reportdate="`echo "$timestamp" | sed 's/[a-z,_,",:,-]//g' | awk '{print $1}'`"
       datediff="`expr $now - $reportdate`"
       if [[ $datediff -gt '1' ]] 
       then exit 1 
       else exit 0 
       fi 
  else curl $opts -u "${user}:${pw}" -H "$h_type" -H "$h_accept" $url_report | python -m json.tool 
  fi 
