#!/bin/bash

  while (( "$#" )); do
    case $1 in
      -s|--server)  shift && name="$1"     ;;
      -p|--param) shift && param="$1"  ;;
      -v|--value) shift && value="$1"  ;;
    esac
    shift
  done

  if [[ -z $name || -z $param || -z $value ]] ; then 
    echo ""
    echo $line
    echo ""
    echo "ERROR: Must include the name option with argument to run this script."
    echo "-s FQDN -p PARAMNAME -v PARAMVALUE" 
    echo ""
    echo $line
    echo ""
    exit 1
  fi 

  server=$name
  opts='-s -k'
  host="ucmnui.associatesys.local"
  url="https://${host}/api/v2"
  url_h="${url}/hosts"
  url_h_name="${url}/hosts/${name}/facts"
  # url_h_name="${url}/hosts/${name}"
  user='ucmadmin'
  pw='unity2018'
  h_type='Content-Type:application/json'
  h_accept='Accept:application/json'

  echo "name:  $server"
  echo "param: $param"
  echo "value: $value"
  echo ""
  curl -kSs -H "Content-type:application/json" -u ${user}:${pw} -X POST $url_h_name -d '{"facts": {"'"${param}"'": "'"${value}"'"}}' | python -m json.tool

