#!/bin/bash

  while (( "$#" )); do
    case $1 in
      -n|--name)  shift && name="$1"     ;;
      -hg|--hostgroup) shift && hg="$1"  ;;
    esac
    shift
  done

  if [[ -z $name || -z $hg ]] ; then 
    echo ""
    echo $line
    echo ""
    echo "ERROR: Must include the name option with argument to run this script."
    echo "-n <SERVER FQDN> -hg <HOST GROUP NAME>" 
    echo ""
    echo $line
    echo ""
    exit 1
  fi 

  server=$name
  opts='-s -k'
  host="ucmnui.associatesys.local"
  url="https://${host}/api/v2"
  url_h="${url}/hosts"
  url_h_name="${url}/hosts/${name}"
  user='ucmadmin'
  pw='unity2018'
  h_type='Content-Type:application/json'
  h_accept='Accept:application/json'

  curl -kSs -H "Content-type:application/json" -u ${user}:${pw} -X PUT $url_h_name -d '{ "host":{"hostgroup_id": "'"${hg}"'" }}' | python -m json.tool


#  while (( "$#" )); do
#    case $1 in
#      -n|--name)  shift && name="$1"     ;;
#      -hg|--hostgroup) shift && hg="$1"  ;;
#    esac
#    shift
#  done
#
#  if [[ -z $name || -z $hg ]] ; then
#    echo ""
#    echo $line
#    echo ""
#    echo "ERROR: Must include the name option with argument to run this script."
#    echo "-n <SERVER FQDN> -hg <HOST GROUP NAME>"
#    echo ""
#    echo $line
#    echo ""
#    exit 1
#  fi
#
#  server=$name
#  opts='-s -k'
#  host="ucmnui.associatesys.local"
#  url="https://${host}/api/v2"
#  url_h="${url}/hosts"
#  url_h_name="${url}/hosts/${name}"
#  user='ucmadmin'
#  pw='unity2018'
#  h_type='Content-Type:application/json'
#  h_accept='Accept:application/json'
#
#  curl -kSs -H "Content-type:application/json" -u ${user}:${pw} -X PUT $url_h_name -d '{ "host":{"hostgroup_id": "'"${hg}"'" }}' | python -m json.tool
#
